name: "Setup Vendor Product Content Type"
description: "Sets up the vendor product content type"
type: "Content type"

install:
  - drupal:node
  - drupal:taxonomy
  - drupal:field
  - drupal:media
  - drupal:media_library
  - drupal:datetime
  - drupal:file
  - drupal:image
  - drupal:link
  - drupal:options
  - drupal:text
  - drupal:editor
  - drupal:ckeditor5
  - drupal:views
